---
abstract: 'Author tests for POD spelling'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Harley Pig <harleypig@gmail.com>'
build_requires:
  Cwd: 0
  Dist::Zilla::Tester: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::More: 0.88
  Test::Spelling: 0
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-PodSpelling
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Pod::Wordlist::hanekomu: 0
  Test::Spelling: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling/issues
  repository: git://github.com/xenoterracide/Dist-Zilla-Plugin-Test-PodSpelling.git
version: 2.1.0
