---
abstract: 'Author tests for POD spelling'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Marcel Gruenauer <hanekomu@gmail.com>'
build_requires:
  Cwd: '0'
  Dist::Zilla::Tester: '0'
  English: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::More: '0.88'
  Test::Requires: '0'
  Test::Script: '1.05'
  Test::Tester: '0'
  utf8: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Test-PodSpelling
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
provides:
  Dist::Zilla::Plugin::PodSpellingTests:
    file: lib/Dist/Zilla/Plugin/PodSpellingTests.pm
    version: '1.112140'
  Dist::Zilla::Plugin::Test::PodSpelling:
    file: lib/Dist/Zilla/Plugin/Test/PodSpelling.pm
    version: '2.006006'
requires:
  Dist::Zilla: '5'
  Dist::Zilla::Plugin::InlineFiles: '0'
  Dist::Zilla::Role::FileFinderUser: '0'
  Dist::Zilla::Role::FileMunger: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  Moose: '0'
  Test::Spelling: '0.12'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/xenoterracide/dist-zilla-plugin-test-podspelling/issues
  homepage: https://metacpan.org/dist/Dist-Zilla-Plugin-Test-PodSpelling
  repository: git://github.com/xenoterracide/dist-zilla-plugin-test-podspelling.git
version: '2.006006'
x_contributors:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'Harley Pig <harleypig@gmail.com>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Randy Stauner <rwstauner@cpan.org>'
