
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling bootstrapped version
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
wordlist
Caleb
Cushing
xenoterracide
Randy
Stauner
randy
Marcel
Gruenauer
marcel
Harley
Pig
harleypig
lib
Dist
Zilla
Plugin
PodSpellingTests
Test
PodSpelling
